Repository kids-first/kf-ui-fhir-data-dashboard, pull requests merged in 2020-08, with the labels that each got.

#107 🐛 Add missing env vars to Docker Compose
  .circleci/config.yml
  docker-compose.yml
Labels: bug

#108 🐛 Remove Auth headers from request if auth is not needed
  src/utils/api.js
Labels: bug

#109 ♻️ Updating old default urls to be the KF dev and QA urls
  cypress/integration/servers.js
  src/config.js
Labels: refactor

#110 🏷 Release 0.3.0
  CHANGELOG.md
Labels: release

#112 💡Updating README to include KF urls
  README.md
Labels: refactor
