Repository kids-first/kf-ui-fhir-data-dashboard, pull requests merged in 2020-04, with the labels that each got.

#58 ✨Configuration UI for adding/updating a server
  README.md
  src/.env.example
  src/actions/index.js
  src/components/App.css
  src/components/App.js
  src/components/Login.css
  src/components/Login.js
  src/components/ReduxApp.js
  src/components/ReduxServerConfiguration.js
  src/components/ResourceDetails.js
  src/components/ServerConfiguration.css
  src/components/ServerConfiguration.js
  src/components/tables/ResultsTable.js
  src/config.js
  src/reducers/index.js
  src/reducers/ontologies.js
  src/reducers/resources.js
  src/reducers/user.js
  src/utils/api.js
  src/utils/common.js
Labels: feature

#59 ♻️Refactoring reducers and server configuration
  README.md
  src/.env.example
  src/actions/index.js
  src/components/App.js
  src/components/Login.css
  src/components/ReduxApp.js
  src/components/ReduxHomepage.js
  src/components/ReduxLogin.js
  src/components/ReduxOntologyHomepage.js
  src/components/ReduxResourceDetails.js
  src/components/ReduxServerConfiguration.js
  src/components/ServerConfiguration.css
  src/components/ServerConfiguration.js
  src/config.js
  src/reducers/app.js
  src/reducers/index.js
  src/reducers/resources.js
  src/utils/api.js
  src/utils/common.js
Labels: refactor

#65 🐳 Dockerize the app
  .circleci/config.yml
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  bin/nginx.conf
  docker-compose.yml
Labels: devops

#63 ♻️Use $snapshot endpoint
  package-lock.json
  package.json
  src/components/App.js
  src/components/Homepage.js
  src/components/ReduxResourceDetails.js
  src/components/ResourceDetails.js
Labels: refactor

#71 🐛Adding statement to update table when props change
  src/components/tables/SortableTable.js
Labels: bug

#69 🐛Use id instead of resource name for $snapshot
  src/components/Homepage.js
  src/components/ReduxHomepage.js
  src/components/SearchBar.js
Labels: bug
