Repository kids-first/kf-ui-fhir-data-dashboard, pull requests merged in 2020-07, with the labels that each got.

#87 ✨Add Timeline to Patient resource
  cypress/fixtures/resourceIdDetails/capabilityStatementReferences.json
  cypress/fixtures/resourceIdDetails/conditionDetails.json
  cypress/fixtures/resourceIdDetails/patientDetails.json
  cypress/fixtures/resourceIdDetails/patientResourceDetails.json
  cypress/fixtures/resourceIdDetails/patientStructureDefinition.json
  cypress/fixtures/resourceIdDetails/resourceDetails.json
  cypress/integration/patientIdDetails.js
  cypress/integration/resourceIdDetails.js
  src/.env.example
  src/components/DataScatterChart.css
  src/components/DataScatterChart.js
  src/components/IdDetails.js
  src/components/tables/Timeline.js
  src/config.js
Labels: feature

#90 ✨ Submit Patient data feature
  package-lock.json
  package.json
  src/components/DataScatterChart.js
  src/components/IdDetails.css
  src/components/IdDetails.js
  src/components/SubmitPatientData.js
  src/components/tables/Timeline.js
  src/utils/api.js
Labels: feature

#94 💄 Additional class to header
  src/components/Header.css
  src/components/Header.js
Labels: bug

#95 ✨ Add Patient tab to attributes details page
  src/components/AttributeDetails.css
  src/components/AttributeDetails.js
  src/components/ReduxAttributeDetails.js
Labels: feature

#96 ♻️ Rearranging tabs on an ID detail page
  cypress/integration/resourceIdDetails.js
  src/components/IdDetails.js
Labels: refactor

#97 ♻️ Adding in links to reference table
  src/components/tables/ReferenceTable.js
Labels: refactor

#98 🐛 Removing duplicate codes and queries from resource details
  src/components/ResourceDetails.js
Labels: bug

#99 🏷 Release 0.1.0
  CHANGELOG.md
  release_maker_cfg.json
Labels: release

#100 💄Change from D3b to KF styling
  public/favicon.ico
  src/components/App.css
  src/components/AppBreadcrumb.css
  src/components/DataBarChart.js
  src/components/Header.css
  src/components/Header.js
  src/components/Homepage.css
  src/components/IdDetails.css
  src/components/ResourceDetails.css
  src/components/tables/SortableTable.css
  src/img/logo.svg
  src/index.css
Labels: refactor

#104 🏷 Release 0.2.0
  CHANGELOG.md
Labels: release
